/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContractorActiveAndInative: typeof import('./components/contractors/ContractorActiveAndInative.vue')['default']
    ContractorSearch: typeof import('./components/contractors/ContractorSearch.vue')['default']
    DeleteTrelloLinkModal: typeof import('./components/modals/DeleteTrelloLinkModal.vue')['default']
    Header: typeof import('./components/header/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PersonActiveAndInative: typeof import('./components/person/ContractorActiveAndInative.vue')['default']
    PersonSearch: typeof import('./components/person/ContractorSearch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snackbar: typeof import('./components/snackbar/index.vue')['default']
  }
}
