/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/contractors/ContractorHome': RouteRecordInfo<'/contractors/ContractorHome', '/contractors/ContractorHome', Record<never, never>, Record<never, never>>,
    '/contracts/ContractDetails': RouteRecordInfo<'/contracts/ContractDetails', '/contracts/ContractDetails', Record<never, never>, Record<never, never>>,
    '/contracts/ContractDetailsReadonly': RouteRecordInfo<'/contracts/ContractDetailsReadonly', '/contracts/ContractDetailsReadonly', Record<never, never>, Record<never, never>>,
    '/contracts/EditContract': RouteRecordInfo<'/contracts/EditContract', '/contracts/EditContract', Record<never, never>, Record<never, never>>,
    '/forms/login/Login': RouteRecordInfo<'/forms/login/Login', '/forms/login/Login', Record<never, never>, Record<never, never>>,
    '/forms/myData/AvatarPhoto': RouteRecordInfo<'/forms/myData/AvatarPhoto', '/forms/myData/AvatarPhoto', Record<never, never>, Record<never, never>>,
    '/forms/myData/FormMyInfo': RouteRecordInfo<'/forms/myData/FormMyInfo', '/forms/myData/FormMyInfo', Record<never, never>, Record<never, never>>,
    '/forms/myData/FormMyPassword': RouteRecordInfo<'/forms/myData/FormMyPassword', '/forms/myData/FormMyPassword', Record<never, never>, Record<never, never>>,
    '/forms/myData/Index': RouteRecordInfo<'/forms/myData/Index', '/forms/myData/Index', Record<never, never>, Record<never, never>>,
    '/process-contacts-person/EditProcessContactPerson': RouteRecordInfo<'/process-contacts-person/EditProcessContactPerson', '/process-contacts-person/EditProcessContactPerson', Record<never, never>, Record<never, never>>,
    '/process-contacts-person/ProcessContactPersonDetails': RouteRecordInfo<'/process-contacts-person/ProcessContactPersonDetails', '/process-contacts-person/ProcessContactPersonDetails', Record<never, never>, Record<never, never>>,
    '/process-contacts-person/ProcessContactPersonDetailsReadonly': RouteRecordInfo<'/process-contacts-person/ProcessContactPersonDetailsReadonly', '/process-contacts-person/ProcessContactPersonDetailsReadonly', Record<never, never>, Record<never, never>>,
    '/requirers/EditRequirer': RouteRecordInfo<'/requirers/EditRequirer', '/requirers/EditRequirer', Record<never, never>, Record<never, never>>,
    '/requirers/RequirerDetails': RouteRecordInfo<'/requirers/RequirerDetails', '/requirers/RequirerDetails', Record<never, never>, Record<never, never>>,
    '/requirers/RequirerDetailsReadonly': RouteRecordInfo<'/requirers/RequirerDetailsReadonly', '/requirers/RequirerDetailsReadonly', Record<never, never>, Record<never, never>>,
    '/services-contractors/EditServiceContractor': RouteRecordInfo<'/services-contractors/EditServiceContractor', '/services-contractors/EditServiceContractor', Record<never, never>, Record<never, never>>,
    '/services-contractors/ServiceContractorDetails': RouteRecordInfo<'/services-contractors/ServiceContractorDetails', '/services-contractors/ServiceContractorDetails', Record<never, never>, Record<never, never>>,
    '/services-contractors/ServiceContractorDetailsReadonly': RouteRecordInfo<'/services-contractors/ServiceContractorDetailsReadonly', '/services-contractors/ServiceContractorDetailsReadonly', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/contractors/ContractorHome.vue': {
      routes: '/contractors/ContractorHome'
      views: never
    }
    'src/pages/contracts/ContractDetails.vue': {
      routes: '/contracts/ContractDetails'
      views: never
    }
    'src/pages/contracts/ContractDetailsReadonly.vue': {
      routes: '/contracts/ContractDetailsReadonly'
      views: never
    }
    'src/pages/contracts/EditContract.vue': {
      routes: '/contracts/EditContract'
      views: never
    }
    'src/pages/forms/login/Login.vue': {
      routes: '/forms/login/Login'
      views: never
    }
    'src/pages/forms/myData/AvatarPhoto.vue': {
      routes: '/forms/myData/AvatarPhoto'
      views: never
    }
    'src/pages/forms/myData/FormMyInfo.vue': {
      routes: '/forms/myData/FormMyInfo'
      views: never
    }
    'src/pages/forms/myData/FormMyPassword.vue': {
      routes: '/forms/myData/FormMyPassword'
      views: never
    }
    'src/pages/forms/myData/Index.vue': {
      routes: '/forms/myData/Index'
      views: never
    }
    'src/pages/process-contacts-person/EditProcessContactPerson.vue': {
      routes: '/process-contacts-person/EditProcessContactPerson'
      views: never
    }
    'src/pages/process-contacts-person/ProcessContactPersonDetails.vue': {
      routes: '/process-contacts-person/ProcessContactPersonDetails'
      views: never
    }
    'src/pages/process-contacts-person/ProcessContactPersonDetailsReadonly.vue': {
      routes: '/process-contacts-person/ProcessContactPersonDetailsReadonly'
      views: never
    }
    'src/pages/requirers/EditRequirer.vue': {
      routes: '/requirers/EditRequirer'
      views: never
    }
    'src/pages/requirers/RequirerDetails.vue': {
      routes: '/requirers/RequirerDetails'
      views: never
    }
    'src/pages/requirers/RequirerDetailsReadonly.vue': {
      routes: '/requirers/RequirerDetailsReadonly'
      views: never
    }
    'src/pages/services-contractors/EditServiceContractor.vue': {
      routes: '/services-contractors/EditServiceContractor'
      views: never
    }
    'src/pages/services-contractors/ServiceContractorDetails.vue': {
      routes: '/services-contractors/ServiceContractorDetails'
      views: never
    }
    'src/pages/services-contractors/ServiceContractorDetailsReadonly.vue': {
      routes: '/services-contractors/ServiceContractorDetailsReadonly'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
